version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8

    working_directory: ~/your-project-directory

    steps:
      - checkout

      - run:
          name: Set up JDK 8
          command: |
            sudo update-java-alternatives -s java-1.8.0-openjdk-amd64

      - run:
          name: Build and Test with Maven
          command: mvn clean install
